import type { Question, ModuleId } from './types';

export const QUESTIONS: Record<ModuleId, Question[]> = {
  starter: [
    // Work
    { id: 'work_what', label: 'In ein bis drei Sätzen: Was machst du oder dein Unternehmen?', type: 'textarea', section: 'Work' },
    { id: 'work_favorite', label: 'Was ist dein Lieblingsteil an dieser Arbeit?', type: 'textarea', section: 'Work' },
    { id: 'work_industry', label: 'Wie würdest du deine Branche jemandem erklären, der noch nie davon gehört hat?', type: 'textarea', section: 'Work' },
    // Mission und Vision
    { id: 'mission_why', label: 'Warum hast du dieses Projekt gestartet? Was war der Auslöser?', type: 'textarea', section: 'Mission und Vision' },
    { id: 'mission_matter', label: 'Warum ist diese Arbeit wichtig?', type: 'textarea', section: 'Mission und Vision' },
    { id: 'mission_goals', label: 'Was sind deine Ziele für die nächsten drei bis sechs Monate?', type: 'textarea', section: 'Mission und Vision' },
    { id: 'mission_world', label: 'Wohin willst du Menschen bringen? Wie sieht die Welt aus, wenn du erfolgreich bist?', type: 'textarea', section: 'Mission und Vision' },
    { id: 'mission_top3', label: 'Was sind die drei wichtigsten Ziele in diesem Bereich? Was sollen Menschen tun?', type: 'textarea', section: 'Mission und Vision' },
    // Audience
    { id: 'audience_know', label: 'Was weißt du über deine Kundinnen und Kunden? Was ist ihnen wichtig?', type: 'textarea', section: 'Audience' },
    { id: 'audience_why', label: 'Warum nutzen Menschen deine Website oder dein Produkt? Warum sollten sie es?', type: 'textarea', section: 'Audience' },
    { id: 'audience_findyou', label: 'Wie finden die meisten Menschen zu dir?', type: 'textarea', section: 'Audience' },
    { id: 'audience_sensitive', label: 'Gibt es Themen, auf die deine Zielgruppe sensibel reagiert?', type: 'textarea', section: 'Audience' },
    { id: 'audience_friend', label: 'Wenn jemand einer Freundin von dir erzählt — was soll diese Person sagen?', type: 'textarea', section: 'Audience' },
    { id: 'audience_core', label: 'Was sind deine Kernbotschaften? Was sollen Menschen verstehen?', type: 'textarea', section: 'Audience' },
    // Brand
    { id: 'brand_competition', label: 'Wer ist deine Konkurrenz? Wodurch unterscheidest du dich?', type: 'textarea', section: 'Brand und Persönlichkeit' },
    { id: 'brand_person', label: 'Wenn deine Marke eine Person wäre — wie würdest du sie beschreiben? Sammle so viele Eigenschaften wie möglich.', type: 'textarea', section: 'Brand und Persönlichkeit' },
    { id: 'brand_inspires', label: 'Wer inspiriert dich, online oder offline? Wem willst du nacheifern?', type: 'textarea', section: 'Brand und Persönlichkeit' },
    { id: 'brand_avoid', label: 'Welche Assoziationen willst du vermeiden? Was würde deine Leserinnen und Leser abschrecken?', type: 'textarea', section: 'Brand und Persönlichkeit' },
    // Workflow
    { id: 'workflow_tools', label: 'Welche Tools nutzt euer Team zum Schreiben und Veröffentlichen?', type: 'textarea', section: 'Workflow' },
    { id: 'workflow_feedback', label: 'Wie haltet ihr Feedback während des Prozesses fest?', type: 'textarea', section: 'Workflow' },
    { id: 'workflow_schedule', label: 'Welcher Update-Rhythmus für veraltete Inhalte ist realistisch?', type: 'select', options: ['Quartalsweise', 'Halbjährlich', 'Jährlich', 'Ad hoc'], section: 'Workflow' },
  ],
  madlibs: [
    // Sentence 1
    { id: 'product_name', label: 'Produktname', type: 'text', section: 'Satz 1', placeholder: 'z.B. North' },
    { id: 'helps_lets', label: 'hilft / lässt', type: 'select', options: ['hilft', 'lässt'], section: 'Satz 1' },
    { id: 'audience_noun', label: 'Zielgruppe (Substantiv)', type: 'text', section: 'Satz 1', placeholder: 'z.B. Athletinnen' },
    { id: 'verb1', label: 'Verb 1', type: 'text', section: 'Satz 1', placeholder: 'z.B. trainieren' },
    { id: 'verb2', label: 'Verb 2', type: 'text', section: 'Satz 1', placeholder: 'z.B. dokumentieren' },
    { id: 'object', label: 'Objekt', type: 'text', section: 'Satz 1', placeholder: 'z.B. ihre Performance' },
    { id: 'verb3', label: 'Verb 3 (Zweck)', type: 'text', section: 'Satz 1', placeholder: 'z.B. wachsen' },
    { id: 'adverb', label: 'Adverb', type: 'text', section: 'Satz 1', placeholder: 'z.B. ohne Plateau' },
    // Sentence 2
    { id: 'signup_join', label: 'Aufruf', type: 'select', options: ['Registriere dich für', 'Werde Teil von'], section: 'Satz 2' },
    { id: 'product_name_2', label: 'Produktname (erneut)', type: 'text', section: 'Satz 2' },
    { id: 'verb4', label: 'Verb', type: 'text', section: 'Satz 2', placeholder: 'z.B. teilen' },
    { id: 'plural_noun', label: 'Plural-Substantiv', type: 'text', section: 'Satz 2', placeholder: 'z.B. Trainings' },
    { id: 'secondary_audience', label: 'Sekundäre Zielgruppe', type: 'text', section: 'Satz 2', placeholder: 'z.B. Coaches' },
  ],
  product: [
    { id: 'pq_what', label: 'Was ist es?', type: 'textarea', section: 'Name & Zweck' },
    { id: 'pq_who', label: 'Für wen ist es? Wie hilft es ihnen oder verbessert ihren Tag?', type: 'textarea', section: 'Name & Zweck' },
    { id: 'pq_can', label: 'Was kann man damit tun? Warum sind diese Features wichtig?', type: 'textarea', section: 'Features & Facetten' },
    { id: 'pq_how', label: 'Wie funktioniert es?', type: 'textarea', section: 'Features & Facetten' },
    { id: 'pq_senses', label: 'Denk an die fünf Sinne. Wie schmeckt, fühlt, sieht, riecht, klingt es?', type: 'textarea', section: 'Features & Facetten' },
    { id: 'pq_made', label: 'Woraus besteht es? Warum diese Materialien? Wie pflegt man es?', type: 'textarea', section: 'Features & Facetten' },
    { id: 'pq_size', label: 'Wie groß ist es? Verschiedene Größen, Farben, Formate?', type: 'textarea', section: 'Features & Facetten' },
    { id: 'pq_packaging', label: 'Hat die Verpackung etwas Besonderes? Passt sie zu etwas oder eignet sich das Ganze als Geschenk?', type: 'textarea', section: 'Features & Facetten' },
    { id: 'pq_cost', label: 'Was kostet es? Wie viele Stücke sind enthalten?', type: 'textarea', section: 'Pricing & Verfügbarkeit' },
    { id: 'pq_where', label: 'Wo bekommt man es?', type: 'textarea', section: 'Pricing & Verfügbarkeit' },
    { id: 'pq_make_time', label: 'Wie lange dauern Herstellung und Verpackung?', type: 'textarea', section: 'Pricing & Verfügbarkeit' },
    { id: 'pq_shipping', label: 'Welche Versandoptionen gibt es? Wie lange dauert die Lieferung?', type: 'textarea', section: 'Pricing & Verfügbarkeit' },
    { id: 'pq_purpose', label: 'Wie passt es zu deiner Mission?', type: 'textarea', section: 'Geschichte erzählen' },
    { id: 'pq_history', label: 'Warum hast du dich entschieden, es zu machen? Was war der Auslöser?', type: 'textarea', section: 'Geschichte erzählen' },
    { id: 'pq_process', label: 'Wie hast du es gemacht? Was hast du dabei gelernt?', type: 'textarea', section: 'Geschichte erzählen' },
    { id: 'pq_competition', label: 'Wie unterscheidet es sich von ähnlichen Dingen?', type: 'textarea', section: 'Geschichte erzählen' },
    { id: 'pq_reputation', label: 'Was sagen Menschen darüber? Was sollen sie sagen?', type: 'textarea', section: 'Geschichte erzählen' },
    { id: 'pq_use_cases', label: 'Wie nutzen Menschen es?', type: 'textarea', section: 'Geschichte erzählen' },
  ],
  casestudy: [
    // Handled by CaseStudyList component, but expose schema for export
    { id: 'cs_name', label: 'Name der Kundin oder des Kunden + Web-Adresse', type: 'text' },
    { id: 'cs_what', label: 'Was hast du für sie gemacht?', type: 'textarea' },
    { id: 'cs_audience', label: 'Wer war die Zielgruppe?', type: 'textarea' },
    { id: 'cs_unique', label: 'Was war einzigartig am Projekt? Habt ihr spannende Probleme gelöst?', type: 'textarea' },
    { id: 'cs_results', label: 'Was waren die Ergebnisse? Welche Metriken habt ihr verbessert?', type: 'textarea' },
    { id: 'cs_quotes', label: 'Gibt es Zitate, Pressestimmen, Testimonials? Links sind willkommen.', type: 'textarea' },
  ],
  brief: [
    { id: 'brief_purpose', label: 'Was ist der Zweck des Projekts? Was ist bisher passiert?', type: 'textarea', section: 'Summary' },
    { id: 'brief_next', label: 'Was passiert als Nächstes?', type: 'textarea', section: 'Summary' },
    { id: 'brief_values', label: 'Was ist der Organisation wichtig?', type: 'textarea', section: 'Company' },
    { id: 'brief_mission', label: 'Was versucht die Organisation zu erreichen? Was ist das übergeordnete Ziel?', type: 'textarea', section: 'Company' },
    { id: 'brief_goals', label: 'Was sind die Ziele dieses Projekts?', type: 'textarea', section: 'Company' },
    { id: 'brief_audience', label: 'Wer ist die primäre und wer die sekundäre Zielgruppe?', type: 'textarea', section: 'Audience' },
    { id: 'brief_needs', label: 'Was brauchen sie?', type: 'textarea', section: 'Audience' },
    { id: 'brief_believe_now', label: 'Was glaubt deine Zielgruppe heute über dich? Ehrlich, auch wenn es wehtut.', type: 'textarea', section: 'Shift', placeholder: 'z.B. Judo ist was für Kinder im Verein.' },
    { id: 'brief_believe_next', label: 'Was soll sie danach glauben, was sie heute noch nicht glaubt?', type: 'textarea', section: 'Shift', placeholder: 'z.B. Judo macht Erwachsene stärker als jedes Gym.' },
    { id: 'brief_action', label: 'Was soll sie konkret tun? Eine Handlung, kein Gefühl.', type: 'textarea', section: 'Shift', placeholder: 'z.B. Probetraining buchen' },
    { id: 'brief_one_thing', label: 'Wenn nur ein Satz hängen bleibt: welcher?', type: 'textarea', section: 'Shift' },
    { id: 'brief_say', label: 'Was wollen wir über das Produkt sagen?', type: 'textarea', section: 'Story' },
    { id: 'brief_narrative', label: 'Was ist das Narrativ?', type: 'textarea', section: 'Story' },
    { id: 'brief_improve', label: 'Wie verbessert das Produkt oder der Service das Leben der Menschen?', type: 'textarea', section: 'Story' },
    { id: 'brief_traits', label: 'Was definiert die Marke? Welche Eigenschaften hat sie?', type: 'textarea', section: 'Style' },
    { id: 'brief_voice', label: 'Wie klingt das Unternehmen? Wie kommt die Persönlichkeit durch?', type: 'textarea', section: 'Style' },
    { id: 'brief_tone', label: 'Wie fühlt sich das Unternehmen gegenüber der Zielgruppe an? Welche Stimmung? Wer spricht?', type: 'textarea', section: 'Style' },
  ],
  style: [
    // Style attributes handled by separate picker component
  ],
  copyedit: [
    { id: 'ce_publisher', label: 'Verlagsname oder Marke', type: 'text', section: 'Allgemein' },
    { id: 'ce_dictionary', label: 'Bevorzugtes Wörterbuch (z.B. Duden, Wahrig)', type: 'text', section: 'Allgemein' },
    { id: 'ce_styleguide', label: 'Style-Manual (z.B. CD-Manual, hauseigener Guide)', type: 'text', section: 'Allgemein' },
    { id: 'ce_latin', label: 'Lateinische Abkürzungen oder deutsche Äquivalente?', type: 'radio', options: ['Latein (z.B. e.g., i.e.)', 'Deutsch (z.B., d.h.)'], section: 'Akronyme & Abkürzungen' },
    { id: 'ce_periods', label: 'Punkte in Akronymen?', type: 'radio', options: ['Mit Punkten', 'Ohne Punkte'], section: 'Akronyme & Abkürzungen' },
    { id: 'ce_caps', label: 'Voll-Kapitälchen oder gemischt?', type: 'radio', options: ['Voll', 'Gemischt'], section: 'Akronyme & Abkürzungen' },
    { id: 'ce_define', label: 'Bei der ersten Nennung definieren?', type: 'radio', options: ['Klammer hinter Begriff', 'Begriff in Klammern'], section: 'Akronyme & Abkürzungen' },
    { id: 'ce_dates', label: 'Datumsformat?', type: 'radio', options: ['1. Mai 2026', '01.05.2026', '2026-05-01'], section: 'Akronyme & Abkürzungen' },
    { id: 'ce_decades', label: 'Wie schreibst du Jahrzehnte? (z.B. 90er, 1990er)', type: 'text', section: 'Zahlen' },
    { id: 'ce_spellnumbers', label: 'Zahlen unter 100 ausschreiben?', type: 'radio', options: ['Ja', 'Nein'], section: 'Zahlen' },
    { id: 'ce_units', label: 'Maßeinheiten — immer als Ziffern?', type: 'radio', options: ['Ja', 'Nein'], section: 'Zahlen' },
    { id: 'ce_percent', label: 'Prozent ausschreiben oder Symbol?', type: 'radio', options: ['Wort', '%'], section: 'Zahlen' },
    { id: 'ce_serial', label: 'Oxford-Komma?', type: 'radio', options: ['Ja', 'Nein'], section: 'Interpunktion' },
    { id: 'ce_hyphen', label: 'Wann verwendest du den Bindestrich? (z.B. bei Komposita)', type: 'textarea', section: 'Interpunktion' },
    { id: 'ce_swiss', label: 'Schweizer Schreibweise (ss statt ß)?', type: 'radio', options: ['Ja', 'Nein'], section: 'Spelling' },
    { id: 'ce_contractions', label: 'Kontraktionen?', type: 'radio', options: ['Ausschreiben', 'Erlaubt'], section: 'Spelling' },
    { id: 'ce_links', label: 'Externe Links?', type: 'radio', options: ['Neuer Tab', 'Selbes Fenster'], section: 'Formatting' },
    { id: 'ce_lists', label: 'Listen-Konventionen (Punkt am Ende? Großschreibung?)', type: 'textarea', section: 'Formatting' },
    // Pflicht-Elemente — was in jeder Produktion drin sein muss
    { id: 'ce_logo', label: 'Welche Logos müssen rein? Welche Version, welche Platzierung?', type: 'textarea', section: 'Pflicht-Elemente' },
    { id: 'ce_contact', label: 'Welche Kontaktdaten oder Links müssen sichtbar sein?', type: 'textarea', section: 'Pflicht-Elemente' },
    { id: 'ce_products', label: 'Welche Produkte müssen zu sehen sein?', type: 'textarea', section: 'Pflicht-Elemente' },
    { id: 'ce_legal', label: 'Welche Rechtstexte oder Kennzeichnungen sind Pflicht? (z.B. Werbung/Anzeige, Bildrechte, Impressum)', type: 'textarea', section: 'Pflicht-Elemente' },
    { id: 'ce_disclaimer', label: 'Gibt es Disclaimer oder Einschränkungen für Text oder Bild?', type: 'textarea', section: 'Pflicht-Elemente' },
  ],
  deepdive: [
    // Herkunft
    { id: 'dd_origin', label: 'Das Problem, das zur Gründung geführt hat: Gibt es das heute noch?', type: 'textarea', section: 'Herkunft' },
    { id: 'dd_folklore', label: 'Welche Geschichten erzählt man sich bei euch intern? Folklore, Rituale, Running Gags?', type: 'textarea', section: 'Herkunft' },
    { id: 'dd_never', label: 'Was würdet ihr nie anbieten, auch nicht für viel Geld?', type: 'textarea', section: 'Herkunft' },
    { id: 'dd_vulnerability', label: 'Was ist eure größte Schwachstelle?', type: 'textarea', section: 'Herkunft' },
    // Wahrnehmung
    { id: 'dd_misperception', label: 'Was ist das größte Missverständnis über eure Marke?', type: 'textarea', section: 'Wahrnehmung' },
    { id: 'dd_associations', label: 'Welche Wörter oder Bilder haben Menschen im Kopf, wenn sie euren Namen hören? Woher kommen die?', type: 'textarea', section: 'Wahrnehmung' },
    { id: 'dd_not_buy', label: 'Wer soll euer Produkt nicht kaufen?', type: 'textarea', section: 'Wahrnehmung' },
    // Rolle im Leben
    { id: 'dd_without', label: 'Wie sähe der Alltag eurer Kundschaft aus, wenn es euch morgen nicht mehr gäbe?', type: 'textarea', section: 'Rolle im Leben' },
    { id: 'dd_dropout', label: 'Wo springen Interessierte kurz vor dem Kauf oder der Buchung ab? Warum?', type: 'textarea', section: 'Rolle im Leben' },
    // Wettbewerb
    { id: 'dd_alternatives', label: 'Was nutzen Menschen statt euch, auch außerhalb eurer Branche?', type: 'textarea', section: 'Wettbewerb' },
    { id: 'dd_competitor_credit', label: 'Wofür ist die Konkurrenz bekannt, wofür ihr auch Credit haben wollt?', type: 'textarea', section: 'Wettbewerb' },
    { id: 'dd_momentum', label: 'Wer hat in eurer Kategorie gerade Momentum? Woran liegt das?', type: 'textarea', section: 'Wettbewerb' },
  ],
};

// Style attributes — 55 adjectives, German + English original
export const STYLE_ATTRIBUTES: { de: string; en: string }[] = [
  { de: 'Genau', en: 'Accurate' },
  { de: 'Lebendig', en: 'Alive' },
  { de: 'Artikuliert', en: 'Articulate' },
  { de: 'Beruhigend', en: 'Calming' },
  { de: 'Herausfordernd', en: 'Challenging' },
  { de: 'Klar', en: 'Clear' },
  { de: 'Schlau', en: 'Clever' },
  { de: 'Fesselnd', en: 'Compelling' },
  { de: 'Knapp', en: 'Concise' },
  { de: 'Selbstsicher', en: 'Confident' },
  { de: 'Konversationell', en: 'Conversational' },
  { de: 'Frisch', en: 'Crisp' },
  { de: 'Direkt', en: 'Direct' },
  { de: 'Eloquent', en: 'Eloquent' },
  { de: 'Vereinnahmend', en: 'Engrossing' },
  { de: 'Faszinierend', en: 'Fascinating' },
  { de: 'Schnell', en: 'Fast-paced' },
  { de: 'Fließend', en: 'Fluid' },
  { de: 'Strömend', en: 'Flowing' },
  { de: 'Freundlich', en: 'Friendly' },
  { de: 'Großzügig', en: 'Generous' },
  { de: 'Aufrichtig', en: 'Heartfelt' },
  { de: 'Ehrlich', en: 'Honest' },
  { de: 'Erhellend', en: 'Illuminating' },
  { de: 'Schneidend', en: 'Incisive' },
  { de: 'Informell', en: 'Informal' },
  { de: 'Tiefgründig', en: 'Insightful' },
  { de: 'Einladend', en: 'Inviting' },
  { de: 'Freudig', en: 'Joyful' },
  { de: 'Vielschichtig', en: 'Layered' },
  { de: 'Leicht', en: 'Light' },
  { de: 'Lebhaft', en: 'Lively' },
  { de: 'Strahlend', en: 'Luminous' },
  { de: 'Bewegend', en: 'Moving' },
  { de: 'Nuanciert', en: 'Nuanced' },
  { de: 'Offen', en: 'Open' },
  { de: 'Geordnet', en: 'Organized' },
  { de: 'Präzise', en: 'Precise' },
  { de: 'Provokativ', en: 'Provocative' },
  { de: 'Zielgerichtet', en: 'Purposeful' },
  { de: 'Lesbar', en: 'Readable' },
  { de: 'Resonant', en: 'Resonating' },
  { de: 'Rhythmisch', en: 'Rhythmic' },
  { de: 'Mitreißend', en: 'Riveting' },
  { de: 'Einfach', en: 'Simple' },
  { de: 'Verlangsamend', en: 'Slowing' },
  { de: 'Solide', en: 'Solid' },
  { de: 'Geradlinig', en: 'Straightforward' },
  { de: 'Stark', en: 'Strong' },
  { de: 'Bedacht', en: 'Thoughtful' },
  { de: 'Transzendent', en: 'Transcendant' },
  { de: 'Vertrauenswürdig', en: 'Trustworthy' },
  { de: 'Nützlich', en: 'Useful' },
  { de: 'Vibrierend', en: 'Vibrant' },
  { de: 'Plastisch', en: 'Vivid' },
];
